# Generated by Django 5.1.4 on 2024-12-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mininba', '0002_excelupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelUpload',
        ),
    ]
