# Generated by Django 5.1.4 on 2024-12-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mininba', '0004_alter_students_sem1_cgpa_alter_students_sem1_sub10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sem1_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem1_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
